/**
 * Client wrapper that generates and saves a game breakdown.
 *
 * Important: this module intentionally does not statically import TanStack
 * server functions. The game detail/add routes lazy-load this file, and this
 * file lazy-loads the server function only when generation runs.
 *
 * AI breakdowns must be genuinely generated by OpenRouter.
 * If OpenRouter or its API key is unavailable, generation fails visibly instead
 * of saving a rule-based fake breakdown.
 */
import { supabase } from "@/integrations/supabase/client";

interface GameRow {
  id: string;
  user_id: string;
  game_date: string;
  court_name: string | null;
  location: string | null;
  game_type: string;
  points: number;
  rebounds: number;
  steals: number;
  blocks: number;
  turnovers: number;
  shots_made: number;
  shots_taken: number;
  minutes_played: number | null;
  notes: string | null;
}

interface PastGame {
  points: number;
  rebounds: number;
  steals: number;
  blocks: number;
  turnovers: number;
  shots_made: number;
  shots_taken: number;
}

interface SummaryResult {
  overview: string;
  strengths: string[];
  improvements: string[];
  next_focus: string;
  tags: string[];
}

interface StoredSummary {
  overview: string | null;
  strengths: string[] | null;
  improvements: string[] | null;
  next_focus: string | null;
  tags: string[] | null;
}

function toSummaryResult(summary: StoredSummary): SummaryResult {
  return {
    overview: summary.overview ?? "",
    strengths: summary.strengths ?? [],
    improvements: summary.improvements ?? [],
    next_focus: summary.next_focus ?? "",
    tags: summary.tags ?? [],
  };
}

async function getExistingSummary(gameId: string): Promise<SummaryResult | null> {
  const { data, error } = await supabase
    .from("game_summaries")
    .select("overview,strengths,improvements,next_focus,tags")
    .eq("game_id", gameId)
    .maybeSingle();

  if (error) {
    console.error("Failed to check existing AI summary:", error.message);
    throw new Error("Could not check whether this game already has an AI breakdown.");
  }

  return data ? toSummaryResult(data) : null;
}

async function getPastGames(userId: string): Promise<PastGame[]> {
  const { data, error } = await supabase
    .from("games")
    .select("points,rebounds,steals,blocks,turnovers,shots_made,shots_taken")
    .eq("user_id", userId);

  if (error) {
    console.error("Failed to load past games for AI summary:", error.message);
    return [];
  }

  return data ?? [];
}

async function generateSummary(game: GameRow, pastGames: PastGame[]): Promise<SummaryResult> {
  const { generateGameSummary } = await import("@/server/summary.functions");
  return await generateGameSummary({
    data: { game, pastGames },
  });
}

export async function generateAndSaveSummary(game: GameRow): Promise<SummaryResult> {
  const existingSummary = await getExistingSummary(game.id);
  if (existingSummary) return existingSummary;

  const pastGames = await getPastGames(game.user_id);
  const result = await generateSummary(game, pastGames);

  const { error } = await supabase.from("game_summaries").insert({
    game_id: game.id,
    user_id: game.user_id,
    overview: result.overview,
    strengths: result.strengths,
    improvements: result.improvements,
    next_focus: result.next_focus,
    tags: result.tags,
  });

  if (error) {
    if (error.code === "23505") {
      const savedSummary = await getExistingSummary(game.id);
      if (savedSummary) return savedSummary;
    }

    console.error("Failed to save AI summary:", error.message);
    throw new Error("AI breakdown was generated but could not be saved.");
  }

  return result;
}
